/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;
import persistencia.PeliculaData;
import persistencia.ProyeccionData;
import modelo.Pelicula;
import modelo.Proyeccion;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Charly Cimino
 */
public class Catalogo extends javax.swing.JInternalFrame {

    /**
     * Creates new form Catalogo
     */
    
    private PeliculaData peliData;
    private ProyeccionData proData;
    
    private DefaultListModel<Pelicula> modeloLista;
    private DefaultTableModel modeloTabla;
    
    private DateTimeFormatter horaFormat = DateTimeFormatter.ofPattern("HH:mm");
    private DateTimeFormatter fechaFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    
    public Catalogo() {
        initComponents();
        peliData = new PeliculaData();
        proData = new ProyeccionData();
        
        modeloLista = new DefaultListModel<>();
        jList1.setModel(modeloLista);
        configurarCabeceraTablaHorarios();
        cargarPeliculasEnLista();
        jList1.addListSelectionListener(e -> {
            
            
            if (e.getValueIsAdjusting()) {
                return;
            }

            
            Pelicula peliculaSeleccionada = jList1.getSelectedValue(); 

            if (peliculaSeleccionada != null) {
                
                List<Proyeccion> proyecciones = proData.buscarProyeccionesPorPelicula(peliculaSeleccionada.getTitulo());
                
               
                cargarTablaHorarios(proyecciones);
            } else {
               
                modeloTabla.setRowCount(0);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBusquedaAvanzada = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jScrollPane1.setViewportView(jList1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Cartelera");

        btnBusquedaAvanzada.setText("Busqueda avanzada");
        btnBusquedaAvanzada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaAvanzadaActionPerformed(evt);
            }
        });

        jButton2.setText("Proximos estrenos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55)
                        .addComponent(jButton2)
                        .addGap(46, 46, 46)
                        .addComponent(btnBusquedaAvanzada)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBusquedaAvanzada)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBusquedaAvanzadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaAvanzadaActionPerformed
        // 1. Obtenemos el "escritorio" (el JDesktopPane) donde vive esta ventana
        javax.swing.JDesktopPane escritorio = (javax.swing.JDesktopPane) this.getParent();

        // 2. Creamos la nueva ventana de búsqueda
        VistaBusquedaAvanzada vistaBusqueda = new VistaBusquedaAvanzada();

        // 3. La agregamos al escritorio y la mostramos
        vistaBusqueda.setVisible(true);
        escritorio.add(vistaBusqueda);
        escritorio.moveToFront(vistaBusqueda);

            // TODO add your handling code here:
    }//GEN-LAST:event_btnBusquedaAvanzadaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        javax.swing.JDesktopPane escritorio = (javax.swing.JDesktopPane) this.getParent();

    // 2. Creamos la nueva ventana de "Estrenos" que acabamos de hacer
    VistaProximosEstrenos vistaEstrenos = new VistaProximosEstrenos();

    // 3. La agregamos al escritorio y la mostramos
    vistaEstrenos.setVisible(true);
    escritorio.add(vistaEstrenos);
    escritorio.moveToFront(vistaEstrenos);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusquedaAvanzada;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<Pelicula> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private void configurarCabeceraTablaHorarios() {
            modeloTabla = new DefaultTableModel() {
                public boolean isCellEditable(int row, int column) { return false; }
            };
            
            modeloTabla.addColumn("Sala");
            modeloTabla.addColumn("Fecha");
            modeloTabla.addColumn("Horario");
            modeloTabla.addColumn("Formato"); 
            modeloTabla.addColumn("Precio");
            jTable1.setModel(modeloTabla);
        }
    
    private void cargarPeliculasEnLista() {
        modeloLista.clear(); 
        
       
        List<Pelicula> peliculas = peliData.listarPeliculasEnCartelera(); 
        
        for (Pelicula p : peliculas) {
            modeloLista.addElement(p);
        }
    }
    
    
    private void cargarTablaHorarios(List<Proyeccion> proyecciones) {
        modeloTabla.setRowCount(0); 
        
        for (Proyeccion pro : proyecciones) {
            
            String formato = pro.isEs3D() ? "3D" : "2D";
            if (pro.isSubtitulada()) {
                formato += " (Subtitulada)";
            }

            modeloTabla.addRow(new Object[]{
                pro.getSala().getNroSala(),
                pro.getHoraInicio().format(fechaFormat),
                pro.getHoraInicio().format(horaFormat), // Solo la hora
                formato,
                "$" + pro.getPrecioLugar()
            });
        }
    }    

}
