/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import persistencia.CompradorData;
import modelo.Comprador;
import java.time.Period;
import modelo.Sala;
/**
 *
 * @author Charly Cimino
 */
public class Clientes extends javax.swing.JInternalFrame {

    CompradorData compradorData = new CompradorData();
    Comprador comprador = new Comprador();
    
    private DefaultTableModel modelo = new DefaultTableModel(){
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
        armarCabecera();
        cargarCompradores(compradorData.obtenerTodosLosCompradores());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EscritorioModificarCliente = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JTNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTDni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JDFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        JTPass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JCBMedioDePago = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        JBGuardarCliente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTClientes = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JTBuscarPorDni = new javax.swing.JTextField();
        JBBuscar = new javax.swing.JButton();
        JBLimpiar = new javax.swing.JButton();
        JBModificar = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clientes");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153)));
        EscritorioModificarCliente.add(jLabel1);
        jLabel1.setBounds(410, 10, 240, 51);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Nombre");

        JTNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTNombreKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DNI");

        JTDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTDniKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("Fecha de Nacimiento");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Pass");

        JTPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTPassKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Medio de pago");

        JCBMedioDePago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Credito", "Debito", "Efectivo", "Transferencia" }));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Guardar Cliente");

        JBGuardarCliente.setText("Guardar");
        JBGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGuardarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(46, 46, 46))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTDni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JDFechaNacimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCBMedioDePago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBGuardarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(JDFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(JTPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JCBMedioDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(JBGuardarCliente)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        EscritorioModificarCliente.add(jPanel1);
        jPanel1.setBounds(10, 100, 450, 480);

        JTClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTClientes);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("Buscar cliente");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("DNI");

        JTBuscarPorDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTBuscarPorDniKeyTyped(evt);
            }
        });

        JBBuscar.setText("Buscar");
        JBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBuscarActionPerformed(evt);
            }
        });

        JBLimpiar.setText("Actualizar");
        JBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLimpiarActionPerformed(evt);
            }
        });

        JBModificar.setText("Modificar");
        JBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JBModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBLimpiar))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(226, 226, 226)
                            .addComponent(jLabel9))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(JTBuscarPorDni, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(57, 57, 57)
                            .addComponent(JBBuscar))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JTBuscarPorDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBLimpiar)
                    .addComponent(JBModificar))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        EscritorioModificarCliente.add(jPanel2);
        jPanel2.setBounds(530, 100, 590, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(EscritorioModificarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 1154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EscritorioModificarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGuardarClienteActionPerformed
        
        // CAMBIO 4: Validaciones de campos vacíos antes de intentar guardar
        if (JTDni.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El DNI es obligatorio.");
            return;
        }
        
        if (JTNombre.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El nombre es obligatorio.");
            return;
        }
        
        if (JDFechaNacimiento.getDate() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha de nacimiento.");
            return;
        }
        
        LocalDate fechaNacimiento = null;
        try {

            java.util.Date fechaElegida = JDFechaNacimiento.getDate();
            fechaNacimiento = fechaElegida.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate fechaActual = LocalDate.now(); // Fecha de hoy


            Period edad = Period.between(fechaNacimiento, fechaActual);


            if (edad.getYears() < 12) {
                javax.swing.JOptionPane.showMessageDialog(this, "El cliente debe ser mayor de 12 años (Edad actual: " + edad.getYears() + ").");
                return;
            }
            

            if (fechaNacimiento.isAfter(fechaActual)) {
                 javax.swing.JOptionPane.showMessageDialog(this, "La fecha de nacimiento no puede ser futura.");
                 return;
            }
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al validar la fecha.");
            return;
        }

        if (JTPass.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "La contraseña es obligatoria.");
            return;
        }

        try {
            int dni = Integer.parseInt(JTDni.getText());
 
            Comprador compradorExistente = compradorData.buscarCompradorDevuelveComprador(dni);
            
            if (compradorExistente != null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: El DNI " + dni + " ya se encuentra registrado en la base de datos.");
                JTNombre.setText("");
            JTDni.setText("");
            JTPass.setText("");
            JDFechaNacimiento.setDate(null);
                return; 
            }
            
            String nombre = JTNombre.getText().trim().replaceAll("\\s+", " ");
            
 
            
            String pass = JTPass.getText();
            String metodoDePago = JCBMedioDePago.getSelectedItem().toString();
            
            // Lógica de guardado
            compradorData.guardarComprador(new Comprador(dni, nombre, pass, metodoDePago, fechaNacimiento));
            
            javax.swing.JOptionPane.showMessageDialog(this, "Cliente guardado exitosamente.");
            
            // Limpiar campos
            JTNombre.setText("");
            JTDni.setText("");
            JTPass.setText("");
            JDFechaNacimiento.setDate(null); // Limpiar fecha
            
            // Actualizar tabla
            refrescarTabla();
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El DNI debe ser un número válido.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
        }
        
        
        

            // TODO add your handling code here:
    }//GEN-LAST:event_JBGuardarClienteActionPerformed

    private void JBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBuscarActionPerformed
        
        String textoBusqueda = JTBuscarPorDni.getText();
        
        if (textoBusqueda.isEmpty()) {
             javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un DNI para buscar.");
             return;
        }
        
        try {
            int dni = Integer.parseInt(textoBusqueda);
            modelo.setRowCount(0);
            
            Comprador compra = compradorData.buscarCompradorDevuelveComprador(dni);
            
            if (compra != null) {
                cargarComprador(compra);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No se encontró cliente con ese DNI.");
                refrescarTabla();
            }
            
            JTBuscarPorDni.setText("");
            
        } catch (NumberFormatException e) {
             javax.swing.JOptionPane.showMessageDialog(this, "DNI inválido.");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_JBBuscarActionPerformed

    private void JBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLimpiarActionPerformed
        
        modelo.setRowCount(0);
        cargarCompradores(compradorData.obtenerTodosLosCompradores());
// TODO add your handling code here:
    }//GEN-LAST:event_JBLimpiarActionPerformed

    private void JBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBModificarActionPerformed
        
        int filaSeleccionada = JTClientes.getSelectedRow();
        
        if(filaSeleccionada == -1 ){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una fila");
            return ;
        }
        
        try {
            int dni = (Integer) modelo.getValueAt(filaSeleccionada, 0);
            
            Comprador compradorParaModificar = compradorData.buscarCompradorDevuelveComprador(dni);
            
            VistaModificarCliente vistaModificarCliente =  new VistaModificarCliente(compradorData,compradorParaModificar,this);
            
            this.getParent().add(vistaModificarCliente);
            
            vistaModificarCliente.setVisible(true);
        }catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(this, "error al abrir la pagina" + e.getMessage());
        }

    // TODO add your handling code here:
    }//GEN-LAST:event_JBModificarActionPerformed

    private void JTDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTDniKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
                    evt.consume();
                    return;
                }
                if (JTDni.getText().length() >= 10 && JTDni.getSelectedText() == null) {
                    evt.consume();
                }
        // TODO add your handling code here:
    }//GEN-LAST:event_JTDniKeyTyped

    private void JTBuscarPorDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTBuscarPorDniKeyTyped
         char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
                    evt.consume();
                    return;
                }
                if (JTDni.getText().length() >= 10 && JTDni.getSelectedText() == null) {
                    evt.consume();
                }
        // TODO add your handling code here:
    }//GEN-LAST:event_JTBuscarPorDniKeyTyped

    private void JTNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTNombreKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && c != ' ') {
            evt.consume();
            return;
        }
        if (JTNombre.getText().length() >= 35 && JTNombre.getSelectedText() == null) {
            evt.consume();
        }
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_JTNombreKeyTyped

    private void JTPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTPassKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
                    evt.consume();
                }
        if (JTPass.getText().length() >= 10 && JTPass.getSelectedText() == null) {
                    evt.consume();
                }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_JTPassKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane EscritorioModificarCliente;
    private javax.swing.JButton JBBuscar;
    private javax.swing.JButton JBGuardarCliente;
    private javax.swing.JButton JBLimpiar;
    private javax.swing.JButton JBModificar;
    private javax.swing.JComboBox<String> JCBMedioDePago;
    private com.toedter.calendar.JDateChooser JDFechaNacimiento;
    private javax.swing.JTextField JTBuscarPorDni;
    private javax.swing.JTable JTClientes;
    private javax.swing.JTextField JTDni;
    private javax.swing.JTextField JTNombre;
    private javax.swing.JTextField JTPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
    
    private void armarCabecera(){
        
        modelo.addColumn("DNI");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("FECHA NACIMIENTO");
        modelo.addColumn("PASS");
        modelo.addColumn("MEDIO DE PAGO");
        
        JTClientes.setModel(modelo);
        
    }
    
    private void cargarCompradores(ArrayList<Comprador> compradores){
        modelo.setRowCount(0);
        for(Comprador comprador : compradores){
            Object[] fila = {
                comprador.getDni(),
                comprador.getNombre(),
                comprador.getFechaNac(),
                comprador.getPass(),
                comprador.getMedioPago()                
            };
            modelo.addRow(fila);
        }
    }
    
    
    private void cargarComprador(Comprador comprador) {
    
    // 1. Limpia la tabla
        modelo.setRowCount(0); 
    
    // 2. (Opcional pero recomendado) 
    //    Verifica si el comprador existe antes de intentar cargarlo.
        if (comprador == null) {
        // No hagas nada si el comprador es nulo 
        // (por ejemplo, si 'buscarComprador' no encontró nada).
            return; 
        }

    // 3. Crea el array para la fila
        Object[] fila = {
            comprador.getDni(),
            comprador.getNombre(),
            comprador.getFechaNac(),
            comprador.getPass(),
            comprador.getMedioPago()
        };
    
    // 4. Añade esa única fila al modelo
        modelo.addRow(fila);
    }


    public void refrescarTabla() {
        cargarCompradores(compradorData.obtenerTodosLosCompradores());
    }
}
