/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.HeadlessException;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import javax.swing.JOptionPane;
import modelo.*;
import persistencia.PeliculaData;
import persistencia.ProyeccionData;
import persistencia.SalaData;

/**
 *
 * @author Cetera Evelyn
 */
public class ModificarProyeccionVista extends javax.swing.JInternalFrame {

    private Proyeccion proyec;
    private ProyeccionData proData;
    private PeliculaData peliData;
    private SalaData salaData;
    private List<Pelicula> listaPelis;
    private List<Sala> listaSalas;
    private List<Proyeccion> listaProyeccion;
    
    public ModificarProyeccionVista(Proyeccion p, ProyeccionData proData, PeliculaData peliData, SalaData salaData) {
        initComponents();
        proyec = p;
        this.proData = proData;
        this.peliData = peliData;
        this.salaData = salaData;
        listaPelis = peliData.listarTodasLasPeliculas();
        listaSalas = salaData.obtenerTodasLasSalas();
        cargarComboPelis();
        cargarComboSalas();
        cargarComboIdiomas();
        cargarHorarios();
        cargarCampos(proyec);
        
    }
    private void cargarComboPelis() {
        for (Pelicula aux : listaPelis) {
            JCBPelicula.addItem(aux);
        }
        JCBPelicula.setSelectedIndex(-1);
    }

    private void cargarComboSalas() {
        for (Sala aux : listaSalas) {
            JCBSala.addItem(aux);
        }
        JCBSala.setSelectedIndex(-1);
    }
    private void cargarHorarios() {
        String[] horarios = {
            "10:00", "10:30", "11:00", "11:30", "12:00", "12:30",
            "13:00", "13:30", "14:00", "14:30", "15:00", "15:30",
            "16:00", "16:30", "17:00", "17:30", "18:00", "18:30",
            "19:00", "19:30", "20:00", "20:30", "21:00", "21:30",
            "22:00", "22:30", "23:00", "23:30"
        };

        JCBHoraInicio.removeAllItems();
        JCBHoraFin.removeAllItems();

        for (String aux : horarios) {
            JCBHoraInicio.addItem(aux);
            JCBHoraFin.addItem(aux);
        }

        JCBHoraInicio.setSelectedIndex(-1);
        JCBHoraFin.setSelectedIndex(-1);
    }

    private void cargarComboIdiomas() {
        String[] idiomas = {"Español", "Inglés", "Portugués", "Italiano", "Frances"};

        JCBIdioma.removeAllItems();
        for (String aux : idiomas) {
            JCBIdioma.addItem(aux);
        }
        JCBIdioma.setSelectedIndex(-1);
    }

    private void cargarCampos(Proyeccion pro){
        JTFID.setText(String.valueOf(pro.getIdProyeccion()));
        JTFID.setEditable(false);
        
        JCBPelicula.setSelectedItem(pro.getPelicula());
        JCBSala.setSelectedItem(pro.getSala());
        JCBIdioma.setSelectedItem(pro.getIdioma());
        
        LocalDateTime inicio = pro.getHoraInicio();
        
        Date fecha = Date.from(inicio.atZone(ZoneId.systemDefault()).toInstant());
        JOptionPane.showMessageDialog(this, "Tipo de dato: " + fecha.getClass().getName());
        // Asegura que sea del tipo correcto
        JDCCalendario.setDate(new java.util.Date(fecha.getTime()));
        
        String inicioStr = inicio.format(DateTimeFormatter.ofPattern("HH:mm"));
        String finStr = pro.getHoraFin().format(DateTimeFormatter.ofPattern("HH:mm"));
        
        JCBHoraInicio.setSelectedItem(inicioStr);
        JCBHoraFin.setSelectedItem(finStr);
        
        if (pro.isEs3D()){
            jCheckBox3DSI.setSelected(true);
        }else {
            jCheckBox3DNO.setSelected(true);
        }
        
        if(pro.isSubtitulada()){
            jCheckBoxSubSI.setSelected(true);
        }else {
            jCheckBoxSubNO.setSelected(true);
        }
        
        JTFPrecioAsiento.setText(String.valueOf(pro.getPrecioLugar()));
        JTFLugaresDispo.setText(String.valueOf(pro.getLugaresDisponibles()));
        JTFLugaresDispo.setEditable(false);
        
        
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jpGuardarProyeccion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JCBPelicula = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        JCBSala = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        JCBIdioma = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox3DSI = new javax.swing.JCheckBox();
        jCheckBox3DNO = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCheckBoxSubSI = new javax.swing.JCheckBox();
        jCheckBoxSubNO = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        JTFPrecioAsiento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        JTFLugaresDispo = new javax.swing.JTextField();
        JDCCalendario = new com.toedter.calendar.JDateChooser();
        JCBHoraInicio = new javax.swing.JComboBox<>();
        JCBHoraFin = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JTFID = new javax.swing.JTextField();
        JBActualizar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Modificar Proyección");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingrese los datos que desea modificar");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 102), null, new java.awt.Color(153, 153, 153)));

        jpGuardarProyeccion.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));
        jpGuardarProyeccion.setToolTipText("Guardar Proyección");

        jLabel3.setText("Pelicula:");

        jLabel4.setText("Sala:");

        jLabel5.setText("Idiomas:");

        jLabel6.setText("¿Es 3D?");

        jCheckBox3DSI.setText("SI");

        jCheckBox3DNO.setText("NO");

        jLabel7.setText("Hora Inicio:");

        jLabel8.setText("Hora Fin:");

        jLabel9.setText("Subtitulada:");

        jCheckBoxSubSI.setText("SI");

        jCheckBoxSubNO.setText("NO");

        jLabel10.setText("Precio Asiento:");

        jLabel11.setText("Lugares Disponibles: ");

        JDCCalendario.setDateFormatString("yyyy-MM-dd");
        JDCCalendario.setDoubleBuffered(false);
        JDCCalendario.setMaxSelectableDate(new java.util.Date(1767236399000L));
        JDCCalendario.setMinSelectableDate(new Date());

        JCBHoraInicio.setSelectedItem(-1);

        JCBHoraFin.setSelectedItem(-1);

        jLabel12.setText("Fecha de Proyección:");

        jButton1.setText("Elegir Asiento");

        jLabel2.setText("ID:");

        javax.swing.GroupLayout jpGuardarProyeccionLayout = new javax.swing.GroupLayout(jpGuardarProyeccion);
        jpGuardarProyeccion.setLayout(jpGuardarProyeccionLayout);
        jpGuardarProyeccionLayout.setHorizontalGroup(
            jpGuardarProyeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGuardarProyeccionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpGuardarProyeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpGuardarProyeccionLayout.createSequentialGroup()
                        .addGroup(jpGuardarProyeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpGuardarProyeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTFLugaresDispo, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(JTFPrecioAsiento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(31, 31, 31))
                    .addGroup(jpGuardarProyeccionLayout.createSequentialGroup()
                        .addGroup(jpGuardarProyeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpGuardarProyeccionLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(60, 60, 60)
                                .addComponent(jCheckBoxSubSI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxSubNO))
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jpGuardarProyeccionLayout.createSequentialGroup()
                .addGroup(jpGuardarProyeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpGuardarProyeccionLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jpGuardarProyeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addGroup(jpGuardarProyeccionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpGuardarProyeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JCBSala, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JCBPelicula, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JCBIdioma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpGuardarProyeccionLayout.createSequentialGroup()
                        .addGroup(jpGuardarProyeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpGuardarProyeccionLayout.createSequentialGroup()
                                .addComponent(jCheckBox3DSI)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox3DNO))
                            .addComponent(JDCCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCBHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCBHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFID, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 70, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpGuardarProyeccionLayout.setVerticalGroup(
            jpGuardarProyeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGuardarProyeccionLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpGuardarProyeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTFID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jpGuardarProyeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCBPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpGuardarProyeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JCBSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jpGuardarProyeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JCBIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpGuardarProyeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCheckBox3DSI)
                    .addComponent(jCheckBox3DNO))
                .addGroup(jpGuardarProyeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpGuardarProyeccionLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel12))
                    .addGroup(jpGuardarProyeccionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JDCCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jpGuardarProyeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JCBHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jpGuardarProyeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JCBHoraFin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jpGuardarProyeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpGuardarProyeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBoxSubSI)
                        .addComponent(jCheckBoxSubNO)))
                .addGap(24, 24, 24)
                .addGroup(jpGuardarProyeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(JTFPrecioAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jpGuardarProyeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFLugaresDispo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        JBActualizar.setText("Actualizar");
        JBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JBActualizar)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpGuardarProyeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jpGuardarProyeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBActualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBActualizarActionPerformed
        try {
            if (JDCCalendario.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar la fecha");
                return;
            }

            LocalDate fecha = JDCCalendario.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            String inicioStr = (String) JCBHoraInicio.getSelectedItem();
            String finStr = (String) JCBHoraFin.getSelectedItem();

            LocalTime inicio = LocalTime.parse(inicioStr);
            LocalTime fin = LocalTime.parse(finStr);

            LocalDateTime horaInicio = LocalDateTime.of(fecha, inicio);
            LocalDateTime horaFin = LocalDateTime.of(fecha, fin);

            Pelicula peli = (Pelicula) JCBPelicula.getSelectedItem();
            Sala sala = (Sala) JCBSala.getSelectedItem();
            String idioma = (String) JCBIdioma.getSelectedItem();
            int precioButaca = Integer.parseInt(JTFPrecioAsiento.getText());
            boolean es3D = jCheckBox3DSI.isSelected();
            boolean subtitulada = jCheckBoxSubSI.isSelected();
            int lugarDispo = Integer.parseInt(JTFLugaresDispo.getText());

            proyec.setPelicula(peli);
            proyec.setSala(sala);
            proyec.setIdioma(idioma);
            proyec.setPrecioLugar(precioButaca);
            proyec.setEs3D(es3D);
            proyec.setSubtitulada(subtitulada);
            proyec.setLugaresDisponibles(lugarDispo);
            proyec.setHoraInicio(horaInicio);
            proyec.setHoraFin(horaFin);

            proData.actualizarProyeccion(proyec);

            JOptionPane.showMessageDialog(this, "Proyección modificiada correctamente, ");

            this.dispose();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Precio, lugar o ID no válido: ");
            ex.getStackTrace();
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Error al modificar la proyección: ");
            e.getStackTrace();
        }

    }//GEN-LAST:event_JBActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBActualizar;
    private javax.swing.JComboBox<String> JCBHoraFin;
    private javax.swing.JComboBox<String> JCBHoraInicio;
    private javax.swing.JComboBox<String> JCBIdioma;
    private javax.swing.JComboBox<Pelicula> JCBPelicula;
    private javax.swing.JComboBox<Sala> JCBSala;
    private com.toedter.calendar.JDateChooser JDCCalendario;
    private javax.swing.JTextField JTFID;
    private javax.swing.JTextField JTFLugaresDispo;
    private javax.swing.JTextField JTFPrecioAsiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox3DNO;
    private javax.swing.JCheckBox jCheckBox3DSI;
    private javax.swing.JCheckBox jCheckBoxSubNO;
    private javax.swing.JCheckBox jCheckBoxSubSI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jpGuardarProyeccion;
    // End of variables declaration//GEN-END:variables
}
