/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;
import persistencia.SalaData;
import modelo.Sala;

/**
 *
 * @author Charly Cimino
 */
public class SalaVista extends javax.swing.JInternalFrame {

    private SalaData salaData;
    /**
     * Creates new form SalaVista
     */
    public SalaVista() {
        initComponents();
        
        this.salaData = new SalaData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jLabel6 = new javax.swing.JLabel();
        EscritorioSala = new javax.swing.JDesktopPane();
        RBEstadoSi = new javax.swing.JRadioButton();
        RBEstadoNo = new javax.swing.JRadioButton();
        botonGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RBApta3DSi = new javax.swing.JRadioButton();
        RBApta3DNo = new javax.swing.JRadioButton();
        JTCapacidad = new javax.swing.JTextField();
        JTNumeroDeSala = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jMenu1.setText("jMenu1");

        buttonGroup2.add(RBEstadoSi);
        RBEstadoSi.setText("Habilidato");

        buttonGroup2.add(RBEstadoNo);
        RBEstadoNo.setText("No habilitado");

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nro de sala");

        jLabel3.setText("Apta 3D");

        jLabel4.setText("Capacidad");

        jLabel5.setText("Estado");

        buttonGroup1.add(RBApta3DSi);
        RBApta3DSi.setText("Si");
        RBApta3DSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBApta3DSiActionPerformed(evt);
            }
        });

        buttonGroup1.add(RBApta3DNo);
        RBApta3DNo.setText("No");
        RBApta3DNo.setFocusCycleRoot(true);
        RBApta3DNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBApta3DNoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("Sala");

        jButton2.setText("Buscar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Modificar");

        jButton4.setText("Salir");

        EscritorioSala.setLayer(RBEstadoSi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioSala.setLayer(RBEstadoNo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioSala.setLayer(botonGuardar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioSala.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioSala.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioSala.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioSala.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioSala.setLayer(RBApta3DSi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioSala.setLayer(RBApta3DNo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioSala.setLayer(JTCapacidad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioSala.setLayer(JTNumeroDeSala, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioSala.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioSala.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioSala.setLayer(jTextField4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioSala.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioSala.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscritorioSala.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioSalaLayout = new javax.swing.GroupLayout(EscritorioSala);
        EscritorioSala.setLayout(EscritorioSalaLayout);
        EscritorioSalaLayout.setHorizontalGroup(
            EscritorioSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscritorioSalaLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(EscritorioSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EscritorioSalaLayout.createSequentialGroup()
                        .addGroup(EscritorioSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(20, 20, 20)
                        .addGroup(EscritorioSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EscritorioSalaLayout.createSequentialGroup()
                                .addComponent(RBEstadoSi)
                                .addGap(31, 31, 31)
                                .addComponent(RBEstadoNo))
                            .addGroup(EscritorioSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(EscritorioSalaLayout.createSequentialGroup()
                                    .addComponent(RBApta3DSi)
                                    .addGap(30, 30, 30)
                                    .addComponent(RBApta3DNo))
                                .addComponent(JTCapacidad)
                                .addComponent(JTNumeroDeSala, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(botonGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(EscritorioSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscritorioSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(EscritorioSalaLayout.createSequentialGroup()
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(78, 78, 78)
                            .addComponent(jButton2)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscritorioSalaLayout.createSequentialGroup()
                            .addGap(292, 292, 292)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscritorioSalaLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(294, 294, 294))
                    .addGroup(EscritorioSalaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(EscritorioSalaLayout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        EscritorioSalaLayout.setVerticalGroup(
            EscritorioSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscritorioSalaLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(EscritorioSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EscritorioSalaLayout.createSequentialGroup()
                        .addGroup(EscritorioSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscritorioSalaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(39, 39, 39)
                                .addGroup(EscritorioSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(EscritorioSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(RBApta3DSi)
                                        .addComponent(RBApta3DNo))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscritorioSalaLayout.createSequentialGroup()
                                .addComponent(JTNumeroDeSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)))
                        .addGap(17, 17, 17)
                        .addGroup(EscritorioSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(JTCapacidad))
                        .addGap(24, 24, 24)
                        .addGroup(EscritorioSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(RBEstadoSi)
                            .addComponent(RBEstadoNo))
                        .addGap(106, 106, 106))
                    .addGroup(EscritorioSalaLayout.createSequentialGroup()
                        .addGroup(EscritorioSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(EscritorioSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(botonGuardar))
                        .addGap(46, 46, 46)))
                .addComponent(jButton4)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(258, 258, 258))
            .addGroup(layout.createSequentialGroup()
                .addComponent(EscritorioSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EscritorioSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RBApta3DSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBApta3DSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBApta3DSiActionPerformed

    private void RBApta3DNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBApta3DNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBApta3DNoActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        
        int nroDeSala = Integer.parseInt(JTNumeroDeSala.getText());
        boolean estado = false;
        if(RBEstadoSi.isSelected()){
            estado = true;
        }if(RBEstadoNo.isSelected()){
            estado = false;
        }
        int capacidad = Integer.parseInt(JTCapacidad.getText());
        boolean Apta3D = false;
        if(RBApta3DSi.isSelected()){
            Apta3D = true;
        }if(RBApta3DNo.isSelected()){
            Apta3D = false;
        }
        
        salaData.guardarSala(new Sala(nroDeSala,Apta3D,capacidad,estado));
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane EscritorioSala;
    private javax.swing.JTextField JTCapacidad;
    private javax.swing.JTextField JTNumeroDeSala;
    private javax.swing.JRadioButton RBApta3DNo;
    private javax.swing.JRadioButton RBApta3DSi;
    private javax.swing.JRadioButton RBEstadoNo;
    private javax.swing.JRadioButton RBEstadoSi;
    private javax.swing.JButton botonGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
