/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vistas;
import java.awt.Component;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.table.DefaultTableModel;
import modelo.Pelicula;
import persistencia.PeliculaData;
/**
 *
 * @author Charly Cimino
 */
public class VistaProximosEstrenos extends javax.swing.JInternalFrame {
    
    
    private PeliculaData peliData;
    private DefaultListModel modeloLista;
    private DefaultTableModel modeloTablaInfo;
    private DateTimeFormatter fechaFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy"); // Formato más amigable

    /** Creates new form VistaProximosEstrenos */
    public VistaProximosEstrenos() {
        initComponents();
        
        peliData = new PeliculaData();
        modeloLista = new DefaultListModel();
        jListEstrenos.setModel(modeloLista);

        // --- Configuración ---
        configurarRenderersDeLista();
        configurarCabeceraTablaInfo();
        cargarEstrenosEnLista();

        // --- CEREBRO (Listener de la Lista) ---
        jListEstrenos.addListSelectionListener(e -> {
            if (e.getValueIsAdjusting()) {
                return;
            }

            Pelicula peliculaSeleccionada = (Pelicula) jListEstrenos.getSelectedValue();
            if (peliculaSeleccionada != null) {
                // MODO 2: Cargar info de la película
                cargarTablaInfoPelicula(peliculaSeleccionada);
            } else {
                modeloTablaInfo.setRowCount(0);
            }
        });
    }
    
    private void configurarCabeceraTablaInfo() {
        modeloTablaInfo = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) { return false; }
        };
        modeloTablaInfo.addColumn("Información");
        modeloTablaInfo.addColumn("Detalle");
        jTableInfo.setModel(modeloTablaInfo);
    }

    private void cargarEstrenosEnLista() {
        modeloLista.clear();
        modeloTablaInfo.setRowCount(0); // Limpia la tabla de detalles
        List<Pelicula> peliculas = peliData.listarProximosEstrenos(); // Llama al nuevo método SQL
        for (Pelicula p : peliculas) {
            modeloLista.addElement(p);
        }
    }

    private void cargarTablaInfoPelicula(Pelicula peli) {
        modeloTablaInfo.setRowCount(0); // Limpia la tabla
        
        modeloTablaInfo.addRow(new Object[]{"Título", peli.getTitulo()});
        modeloTablaInfo.addRow(new Object[]{"Estreno", peli.getEstreno().format(fechaFormat)});
        modeloTablaInfo.addRow(new Object[]{"Director", peli.getDirector()});
        modeloTablaInfo.addRow(new Object[]{"Actores", peli.getActores()});
        modeloTablaInfo.addRow(new Object[]{"Género", peli.getGenero()});
        modeloTablaInfo.addRow(new Object[]{"Origen", peli.getOrigen()});
    }
    
    // REEMPLAZA tu método 'configurarRenderersDeLista' por este:

    private void configurarRenderersDeLista() {

        // 1. Declaramos la variable SIN genéricos
        ListCellRenderer peliRenderer = 

            // 2. Creamos el renderer SIN genéricos
            new DefaultListCellRenderer() { 

            // 3. El método usará 'Object' genérico
            @Override
            public Component getListCellRendererComponent(JList list, 
                                                            Object value, // <-- 'value' es un Object
                                                            int index, 
                                                            boolean isSelected, 
                                                            boolean cellHasFocus) {

                // 4. Llama al método original
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

                // 5. REVISAMOS el tipo y CONVERTIMOS (cast)
                if (value instanceof Pelicula) {
                    // Si es una Película, muestra el título
                    setText(((Pelicula) value).getTitulo());
                } else {
                    // Si es 'null' o cualquier otra cosa
                    setText(""); 
                }
                return this;
            }
        };

        // 6. Ahora SÍ va a compilar
        jListEstrenos.setCellRenderer(peliRenderer);
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEstrenos = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableInfo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jSplitPane1.setDividerLocation(200);

        jScrollPane1.setViewportView(jListEstrenos);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jTableInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableInfo);

        jSplitPane1.setRightComponent(jScrollPane2);

        jLabel1.setText("Proximos estrenos");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(280, 280, 280))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jListEstrenos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTableInfo;
    // End of variables declaration//GEN-END:variables

}
