/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Proyeccion;
import persistencia.ProyeccionData;

/**
 *
 * @author Hueso
 */
public class VistaClienteProyecciones extends javax.swing.JInternalFrame {
    
    private DefaultTableModel modeloTabla;
    private List<Proyeccion> listaProyeccion;
    private DateTimeFormatter horaFormat = DateTimeFormatter.ofPattern("HH:mm");
    private DateTimeFormatter fechaFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    private ProyeccionData proData;
    private VistaClientePrincipal madre;

    public VistaClienteProyecciones(VistaClientePrincipal madre) {
        initComponents();
        proData = new ProyeccionData();
        listaProyeccion = proData.listarTodasLasProyecciones();
        cabecera();
        cargarTabla();
        this.madre = madre;
    }

    private void cabecera() {
        modeloTabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modeloTabla.addColumn("N° Proyección");
        modeloTabla.addColumn("Pelicula");
        modeloTabla.addColumn("Sala");
        modeloTabla.addColumn("¿Es 3D?");
        modeloTabla.addColumn("Idioma");
        modeloTabla.addColumn("Fecha de Proyección");
        modeloTabla.addColumn("Hora Inicio");
        modeloTabla.addColumn("Hora Fin");
        modeloTabla.addColumn("¿Subtitulada?");
        modeloTabla.addColumn("Precio Butaca");
        modeloTabla.addColumn("Butacas disponibles");

        jTableProyecciones.setModel(modeloTabla);
    }

    private void cargarTabla() {
        modeloTabla.setRowCount(0);
        modeloTabla.fireTableDataChanged();

        for (Proyeccion aux : listaProyeccion) {
            String tituloPeli;
            int nroSala;

            if (aux.getPelicula() != null) {
                tituloPeli = aux.getPelicula().getTitulo();
            } else {
                tituloPeli = "Vacio";
            }

            if (aux.getSala() != null) {
                nroSala = aux.getSala().getNroSala();
            } else {
                nroSala = 0;
            }

            String es3d;
            if (aux.isEs3D()) {
                es3d = "Es 3D";
            } else {
                es3d = "Es 2D";
            }

            String sub;
            if (aux.isSubtitulada()) {
                sub = "SI";
            } else {
                sub = "NO";
            }
            modeloTabla.addRow(new Object[]{
                aux.getIdProyeccion(),
                tituloPeli,
                nroSala,
                es3d,
                aux.getIdioma(),
                aux.getHoraInicio().toLocalDate().format(fechaFormat),
                aux.getHoraInicio().toLocalTime().format(horaFormat),
                aux.getHoraFin().toLocalTime().format(horaFormat),
                sub,
                aux.getPrecioLugar(),
                aux.getLugaresDisponibles()

            });
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProyecciones = new javax.swing.JTable();
        btnSiguiente = new javax.swing.JButton();
        btnAtrás = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        jTableProyecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProyecciones);

        btnSiguiente.setText("Siguiente >");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAtrás.setText("< Atrás");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        escritorio.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnSiguiente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnAtrás, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addGap(381, 381, 381)
                .addComponent(btnAtrás)
                .addGap(256, 256, 256)
                .addComponent(btnSiguiente)
                .addContainerGap(374, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente)
                    .addComponent(btnAtrás))
                .addGap(7, 7, 7)
                .addComponent(btnSalir))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
         int filaSelec = jTableProyecciones.getSelectedRow();

        if (filaSelec == -1) {
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una Proyección de la Tabla para continuar.");
            return;
        }

     
            int id = (Integer) modeloTabla.getValueAt(filaSelec, 0);
            Proyeccion p = proData.buscarProyeccionPorID(id);
        madre.getDt().setProyeccion(p);
        madre.avanzarFlujoVenta(2);
        this.dispose();
    }//GEN-LAST:event_btnSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrás;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProyecciones;
    // End of variables declaration//GEN-END:variables
}
