/*

 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Charly Cimino
 */
public class VistaADM extends javax.swing.JFrame {

    /**
     * Creates new form VistaADM
     */
    public VistaADM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        JBPeliculas = new javax.swing.JButton();
        BotonSala = new javax.swing.JButton();
        JBProyeccion = new javax.swing.JButton();
        JBClientes = new javax.swing.JButton();
        JBInformes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setForeground(java.awt.SystemColor.activeCaption);
        escritorio.setPreferredSize(new java.awt.Dimension(1064, 1064));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("ADMINISTRADOR");

        JBPeliculas.setText("Peliculas");
        JBPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBPeliculasActionPerformed(evt);
            }
        });

        BotonSala.setText("Salas");
        BotonSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalaActionPerformed(evt);
            }
        });

        JBProyeccion.setText("Proyeciones");
        JBProyeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBProyeccionActionPerformed(evt);
            }
        });

        JBClientes.setText("Clientes");
        JBClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBClientesActionPerformed(evt);
            }
        });

        JBInformes.setText("Informes");
        JBInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBInformesActionPerformed(evt);
            }
        });

        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(JBPeliculas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(BotonSala, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(JBProyeccion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(JBClientes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(JBInformes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(605, 605, 605))
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(JBPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254)
                .addComponent(BotonSala, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(256, 256, 256)
                .addComponent(JBProyeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(JBClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBInformes, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(179, 179, 179)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonSala, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBProyeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBInformes, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(396, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1627, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBClientesActionPerformed
            
        escritorio.repaint();
        Clientes vistaCliente = new Clientes();
        vistaCliente.setVisible(true);
        escritorio.add(vistaCliente);
        escritorio.moveToFront(vistaCliente);
    }//GEN-LAST:event_JBClientesActionPerformed

    private void BotonSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalaActionPerformed
        
        escritorio.repaint();
        SalaVista salavista = new SalaVista();
        salavista.setVisible(true);
        escritorio.add(salavista);
        escritorio.moveToFront(salavista);
    }//GEN-LAST:event_BotonSalaActionPerformed

    private void JBProyeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBProyeccionActionPerformed
        // TODO add your handling code here:
        escritorio.repaint();
        VistaProyeccion vp = new VistaProyeccion();
        vp.setVisible(true);
        escritorio.add(vp);
        escritorio.moveToFront(vp);
    }//GEN-LAST:event_JBProyeccionActionPerformed

    private void JBPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBPeliculasActionPerformed
        escritorio.repaint();
        PeliculaVista peliculaVista = new PeliculaVista();
        peliculaVista.setVisible(true);
        escritorio.add(peliculaVista);
        escritorio.moveToFront(peliculaVista);
    }//GEN-LAST:event_JBPeliculasActionPerformed

    private void JBInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBInformesActionPerformed
        // TODO add your handling code here:
        escritorio.repaint();
        VistasTicket vistasTicket = new VistasTicket();
        vistasTicket.setVisible(true);
        escritorio.add(vistasTicket);
        escritorio.moveToFront(vistasTicket);
    }//GEN-LAST:event_JBInformesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaADM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSala;
    private javax.swing.JButton JBClientes;
    private javax.swing.JButton JBInformes;
    private javax.swing.JButton JBPeliculas;
    private javax.swing.JButton JBProyeccion;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
