/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;
import persistencia.PeliculaData;
import persistencia.ProyeccionData;
import persistencia.SalaData;
import modelo.Pelicula;
import modelo.Proyeccion;
import modelo.Sala;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.ArrayList;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import javax.swing.ListCellRenderer;
import javax.swing.DefaultListCellRenderer;
import java.awt.Component;
import javax.swing.JList;

/**
 *
 * @author Charly Cimino
 */
public class VistaBusquedaAvanzada extends javax.swing.JInternalFrame {

    private PeliculaData peliData;
    private ProyeccionData proData;
    private SalaData salaData;
    private DefaultTableModel modeloTabla;
    private DateTimeFormatter horaFormat = DateTimeFormatter.ofPattern("HH:mm");
    private DateTimeFormatter fechaFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    
    /**
     * Creates new form VistaBusquedaAvanzada
     */
    public VistaBusquedaAvanzada() {
        initComponents();
        
        ListCellRenderer<Object> peliRenderer = new DefaultListCellRenderer() {
        @Override
        public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (value == null) {
                setText("Todas las Películas");
            }
            return this;
        }
    };
    // Se lo aplicamos al combo
    jcbFiltroPelicula.setRenderer(peliRenderer);

    // 2. Creamos un "Renderer" para el combo de Salas
    ListCellRenderer<Object> salaRenderer = new DefaultListCellRenderer() {
        @Override
        public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (value == null) {
                setText("Todas las Salas");
            }
            return this;
        }
    };
    jcbFiltroSala.setRenderer(salaRenderer);

    // 3. Creamos un "Renderer" para el combo de Horas
    ListCellRenderer<Object> horaRenderer = new DefaultListCellRenderer() {
         @Override
        public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (value == null) {
                setText("Cualquier Hora");
            }
            return this;
        }
    };
    jcbFiltroHora.setRenderer(horaRenderer);
        
        
        
        peliData = new PeliculaData();
        proData = new ProyeccionData();
        salaData = new SalaData();
        cargarHorarios();
        
        
        configurarCabeceraTablaHorarios();
        cargarComboPeliculas();
        cargarComboSalas();
        
        // Carga la tabla con TODOS los resultados al inicio
        cargarTabla(proData.listarTodasLasProyecciones());
        
        
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnFiltrarActionPerformed(evt);
        }
        });
        
        
        btnLimpiarFiltro.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLimpiarFiltroActionPerformed(evt);
        }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcbFiltroPelicula = new javax.swing.JComboBox<>();
        jcbFiltroSala = new javax.swing.JComboBox<>();
        btnFiltrar = new javax.swing.JButton();
        btnLimpiarFiltro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResultados = new javax.swing.JTable();
        jdcFiltroFecha = new com.toedter.calendar.JDateChooser();
        jcbFiltroHora = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jcbFiltroSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFiltroSalaActionPerformed(evt);
            }
        });

        btnFiltrar.setText("Aplicar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnLimpiarFiltro.setText("LimpiarFiltro");
        btnLimpiarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFiltroActionPerformed(evt);
            }
        });

        jTableResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableResultados);

        jcbFiltroHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas las horas", "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        jLabel1.setText("Pelicula");

        jLabel2.setText("Sala");

        jLabel3.setText("Fecha");

        jLabel4.setText("Horario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbFiltroPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jcbFiltroSala, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdcFiltroFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbFiltroHora, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addComponent(btnFiltrar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiarFiltro)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbFiltroPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbFiltroSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFiltrar)
                        .addComponent(btnLimpiarFiltro)
                        .addComponent(jdcFiltroFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcbFiltroHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
    
       Pelicula peliFiltro = (Pelicula) jcbFiltroPelicula.getSelectedItem();
    Sala salaFiltro = (Sala) jcbFiltroSala.getSelectedItem();
    
    LocalDate fechaFiltro = null;
    if (jdcFiltroFecha.getDate() != null) {
        fechaFiltro = jdcFiltroFecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    }
    
    // --- LÓGICA NUEVA ---
    LocalTime horaFiltro = null;
    String horaStr = (String) jcbFiltroHora.getSelectedItem();
    if (horaStr != null) {
        horaFiltro = LocalTime.parse(horaStr);
    }
    // --- FIN LÓGICA NUEVA ---

    // Llamamos al método SQL (que actualizaremos en el paso 3)
    List<Proyeccion> proyeccionesFiltradas = proData.buscarProyeccionesFiltradas(peliFiltro, salaFiltro, fechaFiltro, horaFiltro);
    
    cargarTabla(proyeccionesFiltradas);

    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnLimpiarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFiltroActionPerformed
        jcbFiltroPelicula.setSelectedIndex(-1);
        jcbFiltroSala.setSelectedIndex(-1);
        jdcFiltroFecha.setDate(null);
        jcbFiltroHora.setSelectedIndex(-1); // <-- ¡AÑADE ESTA LÍNEA!

        cargarTabla(proData.listarTodasLasProyecciones());
            // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarFiltroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcbFiltroSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFiltroSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbFiltroSalaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnLimpiarFiltro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableResultados;
    private javax.swing.JComboBox<String> jcbFiltroHora;
    private javax.swing.JComboBox<Pelicula> jcbFiltroPelicula;
    private javax.swing.JComboBox<Sala> jcbFiltroSala;
    private com.toedter.calendar.JDateChooser jdcFiltroFecha;
    // End of variables declaration//GEN-END:variables

    private void configurarCabeceraTablaHorarios() {
            modeloTabla = new DefaultTableModel() {
                public boolean isCellEditable(int row, int column) { return false; }
            };
            modeloTabla.addColumn("Sala");
            modeloTabla.addColumn("Película");
            modeloTabla.addColumn("Fecha");
            modeloTabla.addColumn("Horario");
            modeloTabla.addColumn("Formato");
            modeloTabla.addColumn("Precio");
            jTableResultados.setModel(modeloTabla); // Asegúrate que tu JTable se llame jTableResultados
    }
    
    
    
    private void cargarComboPeliculas() {
        jcbFiltroPelicula.addItem(null); // Opción "Todas"
        List<Pelicula> pelis = peliData.listarPeliculasEnCartelera(); 
        for (Pelicula p : pelis) {
            jcbFiltroPelicula.addItem(p);
        }
        jcbFiltroPelicula.setSelectedIndex(-1);
    }
    
    
    private void cargarComboSalas() {
        jcbFiltroSala.addItem(null); // Opción "Todas"
        List<Sala> salas = salaData.obtenerTodasLasSalas();
        for (Sala s : salas) {
            jcbFiltroSala.addItem(s);
        }
        jcbFiltroSala.setSelectedIndex(-1);
    }
    
    
    private void cargarTabla(List<Proyeccion> proyecciones) {
        modeloTabla.setRowCount(0); // Limpia la tabla
        
        for (Proyeccion pro : proyecciones) {
            String formato = pro.isEs3D() ? "3D" : "2D";
            if (pro.isSubtitulada()) {
                formato += " (Subtitulada)";
            }

            modeloTabla.addRow(new Object[]{
                pro.getSala().getNroSala(),
                pro.getPelicula().getTitulo(),
                pro.getHoraInicio().format(fechaFormat),
                pro.getHoraInicio().format(horaFormat), 
                formato,
                "$" + pro.getPrecioLugar()
            });
        }
    }
    
    // Pega este método nuevo en VistaBusquedaAvanzada.java
private void cargarHorarios() {
    String[] horarios = {
        "10:00", "10:30", "11:00", "11:30", "12:00", "12:30",
        "13:00", "13:30", "14:00", "14:30", "15:00", "15:30",
        "16:00", "16:30", "17:00", "17:30", "18:00", "18:30",
        "19:00", "19:30", "20:00", "20:30", "21:00", "21:30",
        "22:00", "22:30", "23:00", "23:30"
    };

    jcbFiltroHora.removeAllItems(); // Asegúrate de que el combo se llame jcbFiltroHora
    jcbFiltroHora.addItem(null); // Para la opción "Cualquier hora"
    
    for (String aux : horarios) {
        jcbFiltroHora.addItem(aux);
    }
    
    jcbFiltroHora.setSelectedIndex(-1);
}
    
    

}
