/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;
import modelo.TicketCompra;
import modelo.DetalleTicket;
import modelo.LugarAsiento;

/**
 *
 * @author Charly Cimino
 */
public class VistaImprimirEntradaOnline extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaImprimirEntradaOnline
     */
    public VistaImprimirEntradaOnline() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Imprimir Entrada");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Aqui esta su ticket!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel1)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "¡Imprimiendo entrada... Por favor retírela!");
    
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    public void cargarDatosTicket(TicketCompra ticket) {
    // 1. Empiezas con un String vacío
    String recibo = ""; 

    // 2. Usas += para ir agregando texto
    recibo += "-------------- TICKET DE ENTRADA --------------\n";
    recibo += "Código de Retiro: " + ticket.getIdTicket() + "\n";
    recibo += "Fecha de Compra: " + ticket.getFechCompra() + "\n";
    recibo += "Cliente: " + ticket.getComprador().getNombre() + "\n";
    recibo += "DNI: " + ticket.getComprador().getDni() + "\n";
    recibo += "-----------------------------------------------\n\n";

    // Recorres los detalles
    for (DetalleTicket dt : ticket.getDetalles()) {
        recibo += "PELÍCULA: " + dt.getProyeccion().getPelicula().getTitulo() + "\n";
        recibo += "SALA: " + dt.getProyeccion().getSala().getNroSala() + "\n";
        recibo += "FECHA Y HORA: " + dt.getProyeccion().getHoraInicio() + "\n";
        recibo += "IDIOMA: " + dt.getProyeccion().getIdioma() + "\n";
        
        recibo += "BUTACAS: \n";
        for (LugarAsiento asiento : dt.getLugares()) {
            recibo += "   [Fila " + asiento.getFila() + 
                      " - Nro " + asiento.getNumeroAsiento() + "]\n";
        }
        recibo += "Precio Unitario: $" + dt.getProyeccion().getPrecioLugar() + "\n";
        recibo += "Subtotal: $" + dt.getSubtotal() + "\n";
        recibo += "-----------------------------------------------\n";
    }

    recibo += "\nTOTAL PAGADO: $" + ticket.getMonto() + "\n";
    recibo += "===============================================\n";
    recibo += "        ¡Gracias por elegir CinemaCentro!      ";

    // 3. Lo muestras en el área de texto
    jTextArea1.setText(recibo);
}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
