/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Comprador;
import persistencia.CompradorData;
import java.time.Period;

/**
 *
 * @author Charly Cimino
 */
public class VistaModificarCliente extends javax.swing.JInternalFrame {

        
    private CompradorData compradorData;
    private Comprador comprador;
    private Clientes vistaPadre;
    /**
     * Creates new form VistaModificarCliente
     */
    public VistaModificarCliente(CompradorData compradorData,Comprador comprador,Clientes vistaPadre) {
        initComponents();
        this.comprador = comprador;
        this.compradorData = compradorData;
        this.vistaPadre = vistaPadre;
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JTDni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JDFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        JTPass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JBGuardar = new javax.swing.JButton();
        JBSalir = new javax.swing.JButton();
        JCMedioDePago = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Modificar Cliente");

        JTDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTDniKeyTyped(evt);
            }
        });

        jLabel2.setText("DNI");

        jLabel3.setText("Nombre");

        JTNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTNombreKeyTyped(evt);
            }
        });

        jLabel4.setText("Fecha Nacimiento");

        jLabel5.setText("Pass");

        JTPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTPassKeyTyped(evt);
            }
        });

        jLabel6.setText("Medio de pago");

        JBGuardar.setText("Guardar");
        JBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGuardarActionPerformed(evt);
            }
        });

        JBSalir.setText("Salir");
        JBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalirActionPerformed(evt);
            }
        });

        JCMedioDePago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "debito", "credito", "transferencia", "efectivo" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(83, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JBGuardar)
                            .addComponent(JDFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTNombre)
                            .addComponent(JTDni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTPass)
                            .addComponent(JCMedioDePago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(158, 158, 158))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JBSalir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(JDFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JTPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JCMedioDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(JBGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBSalir)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGuardarActionPerformed
        if (JTNombre.getText().trim().isEmpty()) {
             JOptionPane.showMessageDialog(this, "El nombre es obligatorio.");
             return;
        }
        
        if (JTPass.getText().trim().isEmpty()) {
             JOptionPane.showMessageDialog(this, "El pass es obligatorio.");
             return;
        }
        
        if (JDFechaNacimiento.getDate() == null) {
             JOptionPane.showMessageDialog(this, "La fecha de nacimiento es obligatoria.");
             return;
        }
        
        LocalDate fechaNacimiento = null;
        
        try {
        java.util.Date fechaElegida = JDFechaNacimiento.getDate();
        
        // Aquí solo asignamos el valor (ya no ponemos 'LocalDate' al principio)
        fechaNacimiento = fechaElegida.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        LocalDate fechaActual = LocalDate.now();

        Period edad = Period.between(fechaNacimiento, fechaActual);

        if (edad.getYears() < 12) {
            javax.swing.JOptionPane.showMessageDialog(this, "El cliente debe ser mayor de 12 años (Edad actual: " + edad.getYears() + ").");
            return;
        }
        
        if (fechaNacimiento.isAfter(fechaActual)) {
             javax.swing.JOptionPane.showMessageDialog(this, "La fecha de nacimiento no puede ser futura.");
             return;
        }
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al validar la fecha.");
        return;
    }

    if (JTPass.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "La contraseña es obligatoria.");
        return;
    }
        
        try{
            
            int dniSinModificar = comprador.getDni();
            int dni = Integer.parseInt(JTDni.getText());
            
            
            
            String nombre = JTNombre.getText().trim().replaceAll("\\s+", " ");
            String pass = JTPass.getText();
            
            java.util.Date fecha = JDFechaNacimiento.getDate();
        
            fechaNacimiento = fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            String medioDePago = JCMedioDePago.getSelectedItem().toString();
            
            compradorData.actualizarComprador(dniSinModificar,dni, nombre, pass, medioDePago, fechaNacimiento);
            
            JOptionPane.showMessageDialog(this, "Cliente actualizado correctamente.");
            
            if (vistaPadre != null) {
                vistaPadre.refrescarTabla();
            }
            
             this.dispose();
            
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "error " + e.getMessage());
        }
        
       
        // TODO add your handling code here:
    }//GEN-LAST:event_JBGuardarActionPerformed

    private void JBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalirActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_JBSalirActionPerformed

    private void JTDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTDniKeyTyped
        
        // TODO add your handling code here:
    }//GEN-LAST:event_JTDniKeyTyped

    private void JTNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTNombreKeyTyped
        char c = evt.getKeyChar();
                
                if (!Character.isLetter(c) && c != ' ') {
                    evt.consume();
                    return;
                }
                
                if (JTNombre.getText().length() >= 35 && JTNombre.getSelectedText() == null) {
                    evt.consume();
                }
        // TODO add your handling code here:
    }//GEN-LAST:event_JTNombreKeyTyped

    private void JTPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTPassKeyTyped
        char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume();
                }
         if (JTPass.getText().length() >= 10 && JTPass.getSelectedText() == null) {
                    evt.consume();
                }
        // TODO add your handling code here:
    }//GEN-LAST:event_JTPassKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBGuardar;
    private javax.swing.JButton JBSalir;
    private javax.swing.JComboBox<String> JCMedioDePago;
    private com.toedter.calendar.JDateChooser JDFechaNacimiento;
    private javax.swing.JTextField JTDni;
    private javax.swing.JTextField JTNombre;
    private javax.swing.JTextField JTPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    public void cargarDatos(){
        JTDni.setText(String.valueOf(comprador.getDni()));
        
        JTDni.setEditable(false);
        JTNombre.setText(comprador.getNombre());
        JTPass.setText(comprador.getPass());
        

        
        String metodoDePago = comprador.getMedioPago();
        
        for(int i = 0 ; i < JCMedioDePago.getItemCount() ; i++ ){
            
            String metodoDePagoEnLista = JCMedioDePago.getItemAt(i);
            
            if(metodoDePagoEnLista.equalsIgnoreCase(metodoDePago)){
                
                JCMedioDePago.setSelectedIndex(i);
                
                break;
            }
        
        }
        
        LocalDate miLocalDate = comprador.getFechaNac();
        
        Date utilDate = Date.from(miLocalDate.atStartOfDay(ZoneId.systemDefault()).toInstant());
        
        JDFechaNacimiento.setDate(utilDate);
        
    }

}
