/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;
import vistas.*;
import persistencia.*;
import modelo.*;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author y
 */
public class VistasTicket extends javax.swing.JInternalFrame {
    
    private DefaultTableModel modeloTabla;
    private TicketCompraData tcData;
    private DetalleTicketData dtData;
    private PeliculaData pData;
    private CompradorData cData;

    /**
     * Creates new form VistasTicket
     */
    public VistasTicket() {
        initComponents();
        tcData = new TicketCompraData();
        dtData = new DetalleTicketData();
        pData = new PeliculaData();
        cData = new CompradorData();
        
        modeloTabla = new DefaultTableModel();
        jtResultados.setModel(modeloTabla);
        
        cargarComboPelis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtResultados = new javax.swing.JTable();
        jdcFechaCompra = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jbTicketsPorPelicula = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jcbPeliculas = new javax.swing.JComboBox<>();
        jbTicketsPorFecha = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jdcFechaAsistencia = new com.toedter.calendar.JDateChooser();
        jbPeliculaPorVistas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jdcFechaPeliculaVista = new com.toedter.calendar.JDateChooser();
        jbCompradoresPorFecha = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jtResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtResultados);

        jLabel2.setText("Seleccione Pelicula");

        jbTicketsPorPelicula.setText("Generar Informe");
        jbTicketsPorPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTicketsPorPeliculaActionPerformed(evt);
            }
        });

        jLabel3.setText("Seleccione Fecha");

        jcbPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPeliculasActionPerformed(evt);
            }
        });

        jbTicketsPorFecha.setText("Generar Informe");
        jbTicketsPorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTicketsPorFechaActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione Fecha de proyeccion");

        jbPeliculaPorVistas.setText("Generar Informe");
        jbPeliculaPorVistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPeliculaPorVistasActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Pelicula más vista");

        jLabel5.setText("Seleccione Fecha");

        jbCompradoresPorFecha.setText("Generar Informe");
        jbCompradoresPorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCompradoresPorFechaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Fecha con más asistencia");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Informe de tickets vendidos por Pelicula");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Informe de tickets vendidos por Fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jdcFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbTicketsPorFecha))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbTicketsPorPelicula))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jdcFechaAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbCompradoresPorFecha))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jdcFechaPeliculaVista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addComponent(jbPeliculaPorVistas))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbTicketsPorFecha)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jdcFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbTicketsPorPelicula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jdcFechaAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCompradoresPorFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdcFechaPeliculaVista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jbPeliculaPorVistas, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarComboPelis() {    
    List<Pelicula> peliculas = pData.listarTodasLasPeliculas(); 
    for (Pelicula p : peliculas) {        
        jcbPeliculas.addItem(p); 
    }
    
    }
    private void limpiarTabla() {
    modeloTabla.setRowCount(0);
    modeloTabla.setColumnCount(0);
}
    private void jbTicketsPorPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTicketsPorPeliculaActionPerformed
        limpiarTabla();
        Pelicula p = (Pelicula) jcbPeliculas.getSelectedItem();
    if (p == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una película.");
        return;
    }    
        ArrayList<TicketCompra>tickets= tcData.listarTicketsPorPelicula(p.getTitulo());
        
        modeloTabla.addColumn("ID Ticket");
        modeloTabla.addColumn("Fecha Compra");
        modeloTabla.addColumn("Monto");
        modeloTabla.addColumn("Comprador");
        
        for (TicketCompra tc : tickets) {
        modeloTabla.addRow(new Object[]{
            tc.getIdTicket(),
            tc.getFechCompra().toString(),
            tc.getMonto(),
            tc.getComprador().getNombre() 
        });
    }
        
    }//GEN-LAST:event_jbTicketsPorPeliculaActionPerformed

    private void jbTicketsPorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTicketsPorFechaActionPerformed
        limpiarTabla();
        java.util.Date fechaTicket = jdcFechaCompra.getDate();
        if(fechaTicket == null){
          javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha.");
        return;  
        }
        LocalDate fecha = fechaTicket.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        ArrayList<TicketCompra>tickets= tcData.listarTicketsPorFecha(fecha);
        
        modeloTabla.addColumn("ID Ticket");
        modeloTabla.addColumn("Fecha Compra");
        modeloTabla.addColumn("Monto");
        modeloTabla.addColumn("Comprador");
        
        for (TicketCompra tc : tickets) {
        modeloTabla.addRow(new Object[]{
            tc.getIdTicket(),
            tc.getFechCompra().toString(),
            tc.getMonto(),
            tc.getComprador().getNombre() 
        });
    }
    }//GEN-LAST:event_jbTicketsPorFechaActionPerformed

    private void jbPeliculaPorVistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPeliculaPorVistasActionPerformed
        limpiarTabla();
    // 2. Llamar al método (que debes crear) en PeliculaData (o donde sea)
    // Esto requiere una clase "EstadisticaPelicula" que tenga "nombre" y "cantidad"
    // La consulta es: SELECT p.titulo, SUM(dt.cantidad) as total
    // FROM detalle_ticket dt 
    // JOIN proyeccion pr ON dt.idProyeccion = pr.idProyeccion
    // JOIN pelicula p ON pr.idPelicula = p.idPelicula
    // GROUP BY p.titulo
    // ORDER BY total DESC
    // ArrayList<EstadisticaPelicula> stats = pData.getEstadisticasPeliculas(); // Asumiendo que esto existe
    // 3. Mostrar resultados
    modeloTabla.addColumn("Película");
    modeloTabla.addColumn("Entradas Vendidas");
    // for (EstadisticaPelicula stat : stats) {
    //     modeloTabla.addRow(new Object[]{
    //         stat.getNombrePelicula(),
    //         stat.getCantidadVendida()
    //     });
    // }

    // Mensaje temporal mientras no tienes la lógica:
    javax.swing.JOptionPane.showMessageDialog(this, "Esta función aún no está implementada en la capa de persistencia.");       
        
    }//GEN-LAST:event_jbPeliculaPorVistasActionPerformed

    private void jbCompradoresPorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCompradoresPorFechaActionPerformed
        // TODO add your handling code here:
         limpiarTabla();
        java.util.Date fechaAsistencia = jdcFechaPeliculaVista.getDate();
        if (fechaAsistencia == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha de asistencia.");
        return;
    }
        // Debe buscar en detalle_ticket por fechProyeccion, luego buscar el
    // ticket_compra y finalmente el comprador. Usar DISTINCT.
    //ArrayList<Comprador> compradores = cData.buscarCompradoresPorFechaAsistencia(fecha);
    //Mostrar resultados
    }//GEN-LAST:event_jbCompradoresPorFechaActionPerformed

    private void jcbPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPeliculasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcbPeliculasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCompradoresPorFecha;
    private javax.swing.JButton jbPeliculaPorVistas;
    private javax.swing.JButton jbTicketsPorFecha;
    private javax.swing.JButton jbTicketsPorPelicula;
    private javax.swing.JComboBox<modelo.Pelicula> jcbPeliculas;
    private com.toedter.calendar.JDateChooser jdcFechaAsistencia;
    private com.toedter.calendar.JDateChooser jdcFechaCompra;
    private com.toedter.calendar.JDateChooser jdcFechaPeliculaVista;
    private javax.swing.JTable jtResultados;
    // End of variables declaration//GEN-END:variables
}
