/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JOptionPane;
import modelo.Sala;
import persistencia.SalaData;

/**
 *
 * @author Charly Cimino
 */
public class VistaModificarSala extends javax.swing.JInternalFrame {
    
    
    private SalaData salaData;
    private Sala salaModificar;

    /**
     * Creates new form VistaModificarSala
     */
    public VistaModificarSala(SalaData salaData , Sala sala) {
        initComponents();
        
        this.salaData = salaData;
        this.salaModificar = sala;
        
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        JTModificarNroSala = new javax.swing.JTextField();
        JTCapacidad = new javax.swing.JTextField();
        JRApta3DSi = new javax.swing.JRadioButton();
        JTHabilitado = new javax.swing.JRadioButton();
        JBModificar = new javax.swing.JButton();
        JTNoHabilitado = new javax.swing.JRadioButton();
        JTApta3DNo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JBSalir = new javax.swing.JButton();

        jLabel1.setText("ModificarSala");

        buttonGroup1.add(JRApta3DSi);
        JRApta3DSi.setText("Si");

        buttonGroup2.add(JTHabilitado);
        JTHabilitado.setText("Habilitado");

        JBModificar.setText("Modifcar");
        JBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBModificarActionPerformed(evt);
            }
        });

        buttonGroup2.add(JTNoHabilitado);
        JTNoHabilitado.setText("No Habilitado");

        buttonGroup1.add(JTApta3DNo);
        JTApta3DNo.setText("No");

        jLabel2.setText("Nro de sala");

        jLabel3.setText("Apta 3D");

        jLabel4.setText("Capacidad");

        JBSalir.setText("Salir");
        JBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(JTCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTModificarNroSala, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(JRApta3DSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTApta3DNo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JBModificar)
                .addGap(152, 152, 152))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JTHabilitado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTNoHabilitado)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JBSalir)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTModificarNroSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JRApta3DSi)
                    .addComponent(JTApta3DNo)
                    .addComponent(jLabel3))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTHabilitado)
                    .addComponent(JTNoHabilitado))
                .addGap(18, 18, 18)
                .addComponent(JBModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(JBSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBModificarActionPerformed
        
        try {
            int nroSala = salaModificar.getNroSala();
            int capacidad = Integer.parseInt(JTCapacidad.getText());
            boolean apta3D = JRApta3DSi.isSelected();
            boolean habilitado = JTHabilitado.isSelected();
            
            
            salaData.actualizarSala(nroSala, apta3D, capacidad, habilitado);
            
            JOptionPane.showMessageDialog(this, "Sala actualizada con éxito.");
            
            this.dispose();
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La capacidad debe ser un número válido.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar la sala: " + e.getMessage());
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_JBModificarActionPerformed

    private void JBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalirActionPerformed
        
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_JBSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBModificar;
    private javax.swing.JButton JBSalir;
    private javax.swing.JRadioButton JRApta3DSi;
    private javax.swing.JRadioButton JTApta3DNo;
    private javax.swing.JTextField JTCapacidad;
    private javax.swing.JRadioButton JTHabilitado;
    private javax.swing.JTextField JTModificarNroSala;
    private javax.swing.JRadioButton JTNoHabilitado;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    public void cargarDatos(){
        JTModificarNroSala.setText(String.valueOf(salaModificar.getNroSala()));
        JTModificarNroSala.setEnabled(false);
        
        JTCapacidad.setText(String.valueOf(salaModificar.getCapacidad()));
        
        if (salaModificar.getApta3D()) {
            JRApta3DSi.setSelected(true);
        } else {
            JTApta3DNo.setSelected(true);
        }

        // Asumo que tienes JRadioButtons para Estado
        if (salaModificar.isEstado()) {
            JTHabilitado.setSelected(true);
        } else {
            JTNoHabilitado.setSelected(true);
        }
        
    }
    
    
    
    

}
