/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.DetalleTicket;
import modelo.LugarAsiento;
import modelo.Proyeccion;
import modelo.TicketCompra;
import persistencia.DetalleTicketData;
import persistencia.LugarAsientoData;
import persistencia.TicketCompraData;

/**
 *
 * @author Hueso
 */
public class VistaClienteImprimirEntrada extends javax.swing.JInternalFrame {
    VistaClientePrincipal madre;
    TicketCompra tc = new TicketCompra();
    DetalleTicket dt = new DetalleTicket();
    
    TicketCompraData tcd = new TicketCompraData();
    DetalleTicketData dtd = new DetalleTicketData();
    LugarAsientoData lad = new LugarAsientoData();
    
    /**
     * Creates new form VistaClienteImprimirEntrada
     */
    public VistaClienteImprimirEntrada(VistaClientePrincipal madre) {
        initComponents();
        this.madre = madre; 
        this.tc = madre.getTc();
        this.dt = madre.getDt();
        jTextArea1.append(generarTextoTicketSimple());
    }
    
    public String generarTextoTicketSimple() {
    Proyeccion proyeccion = dt.getProyeccion();
    ArrayList<LugarAsiento> asientos = dt.getLugares();
    
    String ticket = "";

    ticket += "----------------- CINEMACENTRO -----------------\n" +  
              "\nPelicula: " + proyeccion.getPelicula().getTitulo() + 
              "\nFecha de proyección: " + proyeccion.getHoraInicio().toLocalDate() + 
              "\nID Proyección: " + proyeccion.getIdProyeccion() +
              "\nHora inicio: " + proyeccion.getHoraInicio().toLocalTime() + 
              "\nHora Finalización: " + proyeccion.getHoraFin().toLocalTime() +
              "\nSala: " + proyeccion.getSala().getNroSala() +
              "\nCantidad de lugares: " + asientos.size() +
              "\nAsiento/s: " + dt.asientosToString() +
              "\nComprador: " + tc.getComprador().getNombre() + 
              "\nDNI: " + tc.getComprador().getDni() +
              "\nMedio de pago: " + tc.getComprador().getMedioPago() +
              "\nFecha de compra: " + tc.getFechCompra() +
              "\nSubtotal: " + dt.getSubtotal() +  
              "\nTotal + I.V.A: $" + tc.getMonto() +  
              "\n\n********* GRACIAS POR SU COMPRA **********\n";
    
    return ticket;
}
    
    public void registrarEntrada(){
        try{
           tcd.guardarTicketCompra(tc); 
           int idTicket = tc.getIdTicket();
           dtd.guardarDetalleTicketCompra(dt, idTicket);
           JOptionPane.showMessageDialog(null, "Ticket registrado exitosamente!");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al registrar compra");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnAtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnFinal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1137, 760));

        btnAtras.setText("< Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\n");
        jScrollPane1.setViewportView(jTextArea1);

        btnFinal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnFinal.setText("Finalizar Compra");
        btnFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(btnAtras, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnFinal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtras)
                .addGap(416, 416, 416)
                .addComponent(btnFinal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(334, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(286, 286, 286))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAtras))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnFinal)
                .addGap(24, 24, 24))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Imprimir Entrada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(302, 302, 302))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalActionPerformed
        // TODO add your handling code here:
        registrarEntrada();
        this.dispose();
    }//GEN-LAST:event_btnFinalActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        madre.avanzarFlujoVenta(3);
    }//GEN-LAST:event_btnAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnFinal;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
